name: gsheet_to_arb_example
description: Example of how to use ghseet_to_arb plugin

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl:
  intl_translation: ^0.17.9

dev_dependencies:
  gsheet_to_arb: ^0.1.7
#    path: ../
  test: ^1.5.3
  mockito: ^4.0.0  

gsheet_to_arb: 
  arb_file_prefix: 'intl'
  localization_file_name: 'l10n'
  output_directory: 'lib/l10n'
  generate_code: true
  add_context_prefix: false
  gsheet: 
    auth_file: './gsheet_to_arb.yaml'
    category_prefix: "# "
    document_id: '1CwFRjtiCmCl8yvP55yBT70h-Yt00CcigD816hsGo7KU'
    sheet_id: '0'
