name: gsheet_to_arb
version: 0.1.0
author: Marcin Marek Goca≈Ç <marcin.gocal@gmail.com>
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  analyzer: '>=0.39.0 <0.40.0'
  args: '>=0.12.1 <2.0.0'
  dart_style: ^1.0.0
  intl: '>=0.16.0 <0.17.0'
  path: '>=0.9.0 <2.0.0'
  googleapis_auth: ^0.2.6
  googleapis: ^0.53.0
  code_builder: ^3.1.3
  intl_translation: ^0.17.7
  json_annotation: ^3.0.1
  file_utils: ^0.1.1
  logging: ^0.11.3+2
  recase: ^2.0.0+1

dev_dependencies:
  test: ^1.5.3
  build_runner: ^1.0.0
  json_serializable: ^3.2.5