name: gsheet_to_arb
version: 0.1.0
description: Imports Application Resource Bundle (ARB) from Google Sheets documents

homepage: https://github.com/gocal/gsheet_to_arb

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  args: '>=1.5.2 <2.0.0'
  dart_style: '>=1.3.3 <2.0.0'
  intl: '>=0.16.0 <0.17.0'
  path: '>=1.6.4 <2.0.0'
  googleapis_auth: ^0.2.6
  googleapis: ^0.54.0
  code_builder: ^3.1.3
  intl_translation: ^0.17.9
  json_annotation: ^3.0.1
  file_utils: ^0.1.1
  logging: ^0.11.3+2
  recase: ^3.0.0
  quiver: 2.0.5 
  yaml: ^2.2.0
  petitparser: '>=1.1.3 <3.0.0'

dev_dependencies:
  analyzer: '>=0.39.0 <0.40.0'
  test: ^1.5.3
  build_runner: ^1.0.0
  json_serializable: ^3.2.5
